name: Python package

on:
  push:
    branches:
      # Set this to "main" or "master" or whatever your main branch is called
      - main
    paths:
      - hw03/**
      
jobs:
  lint:

    runs-on: self-hosted
    strategy:
      matrix:
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pylint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint
          pip install boto3
          pip install moto
          pip install botocore
          

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files 'hw03/*.py')

  test:

    runs-on: self-hosted
    strategy:
      matrix:
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f hw03/requirements.txt ]; then pip install -r hw03/requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          role-session-name: MySessionName

      - name: Run all your pytest tests in your code
        run: |
          pytest hw03/*.py
