# This yaml only pushes the code to the existing lambda. You must create
#  the lambda function(s) in the AWS Console first, before triggering the pipeline. 
# Source:  https://www.whitespectre.com/ideas/multiple-aws-lambda-deployment-with-github-actions/
on:
  push:
    branches:
      - main
    paths:
      - hw04/**
jobs:
  deploy1:
    name: Deploy lambda code for S3 trigger
    # Your repo MUST be in a UConn GitHub Organization that has been configured with RH Runners. 
    # This is a manual task that needs to be completed by the UConn School of Business IT staff.
    # The runs-on value must be "self-hosted" to leverage the runner .
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
          
      # Setp AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # The first parameter can be whatever you want to name your zip file. Really does not matter.
      #   just make sure you use the same file name in the next step below.
      # The second parameter should be the file path of your local lambda code you want to deploy
      - name: Zip python code
        run: zip -j hw04-code.zip ./hw04/lambda.py
        
      # TODO: Change the --function-name value to match your function name in AWS
      - name: Deploy python code to lambda
        run: aws lambda update-function-code --function-name=hw04-zhh20013-1 --zip-file=fileb://hw04-code.zip

      # Deploy second Lambda (delete handler)
      - name: Zip delete handler
        run: zip -j hw04-delete-code.zip ./hw04/lambda_delete.py
        
      - name: Deploy delete handler
        run: aws lambda update-function-code --function-name=hw04-zhh20013-2 --zip-file=fileb://hw04-delete-code.zip

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest boto3

      - name: Run tests
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
        run: pytest hw04/*.py -v
